.Dd $Mdocdate: July 02 2026$
.Dt ISH 1
.Os
.Sh NAME
.Nm ish
.Nd I See and Hear
.Sh SYNOPSIS
.Nm ish
.Ar file
.Sh DESCRIPTION
.Nm ish
is a program to record audio and video sources and output
them to a local file or a streaming website. 

It allows configurations through a series of commands in 
order to match the users preferences.
.Sh COMMANDS
Commands in
.Nm ish
are attached to modes where 0 and 1 are video and audio.

Depending on the mode in which
.Nm ish
is some commands will not run (the default mode is 0).
.Sh AUTHORS
.An Onana Onana Xavier Manuel Aq Mt xavier@onana.net
